baseURL = "http://dineshs91.github.io/blog/"
languageCode = "en-us"
title = "My thoughts and adventures"
theme = "vienna"
copyright = "Copyleft; Feel free to steal"
canonifyurls = true
paginate = 5

[params]
twitter = "SDinesh91"
github = "Dineshs91"
author = "Dinesh S"
authorlocation = "India"
subtitle = "Have no restrictions in your imaginations"
bio = "Curious programmer, love to learn new concepts and open source enthusiast."
ga_api_key = "UA-42311420-3"
disqus = "Dineshs91"
projects = "post/projects"
